/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardTransferRouteImport } from './routes/dashboard.transfer'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardLoansRouteImport } from './routes/dashboard.loans'
import { Route as DashboardCryptoRouteImport } from './routes/dashboard.crypto'
import { Route as DashboardCardsRouteImport } from './routes/dashboard.cards'
import { Route as DashboardBeneficiariesRouteImport } from './routes/dashboard.beneficiaries'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOtpRouteImport } from './routes/admin.otp'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminCardsRouteImport } from './routes/admin.cards'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTransferRoute = DashboardTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoansRoute = DashboardLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCryptoRoute = DashboardCryptoRouteImport.update({
  id: '/crypto',
  path: '/crypto',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCardsRoute = DashboardCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBeneficiariesRoute = DashboardBeneficiariesRouteImport.update({
  id: '/beneficiaries',
  path: '/beneficiaries',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOtpRoute = AdminOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCardsRoute = AdminCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cards': typeof AdminCardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/otp': typeof AdminOtpRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/dashboard/beneficiaries': typeof DashboardBeneficiariesRoute
  '/dashboard/cards': typeof DashboardCardsRoute
  '/dashboard/crypto': typeof DashboardCryptoRoute
  '/dashboard/loans': typeof DashboardLoansRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/transfer': typeof DashboardTransferRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/services'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/chat'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/otp'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/login'
    | '/dashboard/beneficiaries'
    | '/dashboard/cards'
    | '/dashboard/crypto'
    | '/dashboard/loans'
    | '/dashboard/profile'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/services'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/chat'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/otp'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin/login'
    | '/dashboard/beneficiaries'
    | '/dashboard/cards'
    | '/dashboard/crypto'
    | '/dashboard/loans'
    | '/dashboard/profile'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/services'
    | '/admin/audit'
    | '/admin/cards'
    | '/admin/chat'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/otp'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/transactions'
    | '/admin_/login'
    | '/dashboard/beneficiaries'
    | '/dashboard/cards'
    | '/dashboard/crypto'
    | '/dashboard/loans'
    | '/dashboard/profile'
    | '/dashboard/transactions'
    | '/dashboard/transfer'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/transfer': {
      id: '/dashboard/transfer'
      path: '/transfer'
      fullPath: '/dashboard/transfer'
      preLoaderRoute: typeof DashboardTransferRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/loans': {
      id: '/dashboard/loans'
      path: '/loans'
      fullPath: '/dashboard/loans'
      preLoaderRoute: typeof DashboardLoansRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crypto': {
      id: '/dashboard/crypto'
      path: '/crypto'
      fullPath: '/dashboard/crypto'
      preLoaderRoute: typeof DashboardCryptoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cards': {
      id: '/dashboard/cards'
      path: '/cards'
      fullPath: '/dashboard/cards'
      preLoaderRoute: typeof DashboardCardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/beneficiaries': {
      id: '/dashboard/beneficiaries'
      path: '/beneficiaries'
      fullPath: '/dashboard/beneficiaries'
      preLoaderRoute: typeof DashboardBeneficiariesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/otp': {
      id: '/admin/otp'
      path: '/otp'
      fullPath: '/admin/otp'
      preLoaderRoute: typeof AdminOtpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cards': {
      id: '/admin/cards'
      path: '/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AdminCardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCardsRoute: typeof AdminCardsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOtpRoute: typeof AdminOtpRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCardsRoute: AdminCardsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOtpRoute: AdminOtpRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardBeneficiariesRoute: typeof DashboardBeneficiariesRoute
  DashboardCardsRoute: typeof DashboardCardsRoute
  DashboardCryptoRoute: typeof DashboardCryptoRoute
  DashboardLoansRoute: typeof DashboardLoansRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardTransferRoute: typeof DashboardTransferRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBeneficiariesRoute: DashboardBeneficiariesRoute,
  DashboardCardsRoute: DashboardCardsRoute,
  DashboardCryptoRoute: DashboardCryptoRoute,
  DashboardLoansRoute: DashboardLoansRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardTransferRoute: DashboardTransferRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
